### ISSUE TITLE
[FEATURE] Add top navigation bar

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap-apps#47]
## Description
Similar to Wazimap, let's add top navigation bar to HURUmap to make it easier to find data from a long list of visualisations.

## Screenshots

<img width="1280" alt="screen shot 2018-01-15 at 16 12 59" src="https://user-images.githubusercontent.com/877919/34944016-03967378-fa0f-11e7-91ec-70fa55944135.png">

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Add Bootstrap affix for the fixed nav
- [x] Override the base `profile_detail.html` and add the the nav 
- [x] The nav code should be added [here]
- [x] Add nav to Kenya Instance
- [ ] Add nav to Uganda Instance
(https://github.com/CodeForAfrica/HURUmap/blob/c0a5dbd1518fd25c665d6e142f79f2a38a377c6e/hurumap_ke/templates/profile/profile_detail.html#L5) for each of the country profiles

**Comment by phillipahereza** [comment]
@DavidLemayian don't you think this should be implemented in each of the country instances because they all have different categories of data they display.
