### ISSUE TITLE
[FEATURE] Add entity (person/organisation) functionality

### ISSUE THREAD

**Issue by phillipahereza** [CodeForAfrica/HURUmap-apps#52]
## Description

HURUmap / Wazimap helps to answer **where** (through geographies) and **what** (through the data tables) in regards to data collected. To improve how we help users _find the stories behind the data_, we should look to the [five Ws](https://en.wikipedia.org/wiki/Five_Ws) which are some of the questions whose answers are considered basic in information gathering or problem solving;

- Who was involved?
- What happened?
- When did it take place?
- Where did it take place?
- Why did that happen?

Entity data, a person or organisation, help to answer the question of **who** is involved. We should therefore look at how we can provide this data/functionality on HURUmap.

## Tasks

To achieve this, we will look to start with politician data as they are the representatives/leaders of administrative boundaries. To achieve this, we will:

- [ ] Create a schema for entity data modelling on [FollowTheMoney](https://alephdata.github.io/followthemoney/)
- [ ] Scrape initial politician data for Kenya
- [ ] Create a template for displaying this information
- [ ] Document how to add entity data

**Comment by kilemensi** [comment]
Shouldn't this be done in CodeForAfrica/HURUmap @phillipahereza?

**Comment by kilemensi** [comment]
Migrated to PT
