### ISSUE TITLE
[WAJIBISHA] Add Contact Information to the Footer

### ISSUE THREAD

**Issue by phillipahereza** [CodeForAfrica/HURUmap-apps#56]
## Description
Add contact information and links to Wajibisha/PesaCheck social media

## Tasks
- [x] Add Contact details to the footer
- [x] Add social media links to the footer
- [x] Remove placeholder text from about us page
- [x] Add the contact details to about us page
- [x] Add the team images
- [x] Remove search bar
- [x] There’s a typo in the title text --> Some of the promises *We’re* Tracking.
- [x] Also, the styling (blue and bold) is different from the one on the county page (and other pages) that reads All the promises (black and lower case) - should be the same
- [x] Remove watch and congratulate button
- [x] Style dropdowns on all promises page
- [x] Increase margin betweem home page cards and testimonial

**Comment by DavidLemayian** [comment]
Closed by #78
