### ISSUE TITLE
[BUG] GDAL + pip setup broken on Mac

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap-apps#66]
## Description
Setting up development environment on Mac is broken. We had to downgrade GDAL version installed using [git checkout](https://gist.github.com/czarneckid/1536207/d643929cd28cbf853275ee0ba495975a42779549) because it's not a versioned and the latest `libsass` doesn't support the `@include normalize.min` line in `_censusreporter.scss`.

Also the latest WhiteNois v4 is broken. 

How to install GDAL:

```
brew uninstall gdal
brew tap osgeo/osgeo4mac && brew tap --repair
brew install jasper netcdf
brew install gdal --with-complete --with-unsupported
brew link --force gdal2
brew install gdal-python

# Workaround until 2.3.1 released - https://github.com/OSGeo/gdal/issues/674
export PYTHONPATH=/usr/local/Cellar/gdal2-python/2.3.0/lib/python2.7/site-packages 

pip install "GDAL==2.3" "Shapely>=1.5.13"
```

## Screenshots
N/A

## Files

- [Homebrew versions](https://docs.brew.sh/Versions.html)
- [GDAL Formulat at 1.11.5_4](https://github.com/Homebrew/homebrew-core/blob/db0b0e61ec51a1b3ccc9977d00bc00374700d396/Formula/gdal.rb)
- [Broken `_censusreporter.scss`](https://github.com/OpenUpSA/wazimap/blob/master/wazimap/static/css/_censusreporter.scss#L1)
- [SASS changelog](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html)
- [WhiteNoise changelog](http://whitenoise.evans.io/en/latest/changelog.html#v4-0b4)

## To Reproduce
Recreate virtual environment and run pip install requirements. Also any `brew upgrade` if GDAL installed with Homebrew should bring up the issue version issue.

## Tasks

- [x] Document using GDAL options above
- [x] Add versioning to https://github.com/OSGeo/homebrew-osgeo4mac
- [x] Include specific version of libsass in requirements `libsass==0.13.3`
- [x] Include specific version of whitenoise in requirements `whitenoise==3.3.1`
- [x] 🤔

**Comment by DavidLemayian** [comment]
All fixed with Docker.
