### ISSUE TITLE
Package HURUmap

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap-apps#68]
## Description
To improve ease for reuse, we should move `hurumap` module from this repo and rename this one HURUmap-apps.

## \*\*IMPORTANT UPDATE:**
If you're actively developing HURUmap, you'll have to change your origin link **immediately** i.e

```sh
$ git remote set-url origin https://github.com/CodeForAfrica/HURUmap-apps.git
```

## Tasks

- [x] Rename this repo to HURUmap-apps
- [x] Create new repo and move `hurumap`
- [ ] Delete hurumap app and use hurumap package instead
- [ ] Write tests to run on CI
- [ ] Add deployment from CI
- [ ] Announce + document changes
