### ISSUE TITLE
Add embed map functionality 

### ISSUE THREAD

**Issue by KhadijaMahanga** [CodeForAfrica/HURUmap-apps#70]
## Description
Just as how a user is able to embed Charts on HURUmap, we want to add a functionality for a user be able to embed HURUmap profile maps and able to use   it else where.

## Screenshots
N/A

## Files
- [Profile Details](https://github.com/CodeForAfrica/HURUmap-apps/blob/master/hurumap_tz/templates/profile/profile_detail.html)
- Views and Urls Page

## Tasks
Below are tasks that can achieve this:
- [ ] Create a function that will regenerate profile map 
- [ ] Create a template for displaying the information
- [ ] Add a link on profile page that will pop up a light box with iframe code of embed the map

**Comment by kilemensi** [comment]
Migrated to PT
