### ISSUE TITLE
[WAJIBISHA] Design Feedback

### ISSUE THREAD

**Issue by yazminjumaali** [CodeForAfrica/HURUmap-apps#74]
## Description
Design mockups for the Wajibisha promise tracker have been implemented. Using this issue to share comments / feedback / changes relevant to the platform.

## Screenshots

**Home Page**

- Thematic Icons

<img width="850" alt="screen shot 2018-06-13 at 8 19 36 am" src="https://user-images.githubusercontent.com/33617191/41332088-0076abc2-6ee5-11e8-9109-60f96d4992e2.png">

- Footer

<img width="1271" alt="screen shot 2018-06-13 at 8 23 58 am" src="https://user-images.githubusercontent.com/33617191/41331844-d8ed6916-6ee3-11e8-883b-9a3319628d24.png">

**Nairobi County Page**
<img width="1271" alt="screen shot 2018-06-13 at 11 08 42 am" src="https://user-images.githubusercontent.com/33617191/41339858-9d3583d4-6efe-11e8-9336-f890fa081ac2.png">

**Questions:**

_Articles Page_
1. What happened to the Articles page its absent?

_Home Page_
2. The retweet + like buttons don't function is that intentional?
3. I thought the tweets would redirect to a twitter account, right now its static. Whats the plan?
4. Promise tracker menu button doesn't lead to a different page from the home page. Was this the intended user journey?

_Nairobi County Page_
5. How is 'Days in office' updated?
6. The social media share button under "Category" section leads to PesaCheck account. Thought it would lead user to embed to their own account?
7. When I switch from Category filter to ALL the social media share buttons don't function?
8. I'm confused by the filter labels that change as the filter options change. The overview box shows: Promises fulfilled, Promises not fulfilled, Promises in progress, Promises stalled, which matches with the filter option to group by category but is different for the option to group by ALL. The latter introduces filter by Altered promises and Five year plans but I can't filter to see promises done/fulfilled or stalled. I'm I missing something?

## Tasks
Home page:
- [ ] Correct spelling + space errors below thematic icons (circled red)
- [ ] Correct spelling errors on the footer (circled red)
- [ ] Add hyperlinks to tools / projects (underlined purple)
- [ ] Adjust font/ logo sizes (circled green)
- [ ] Add CfK logo

Nairobi County Page:
- [ ] Correct spelling + space errors

About page:
- [ ] Team roles is a bit confusing, let's keep it simple
Phillip Ahereza, Code for Africa Software Developer
Eric Mugendi, PesaCheck Editor
Nduta Waweru, Wajibisha Lead and Journalist
Yazmin Jumaali, Code for Africa Project Manager
Brenda Nyokabi, Code for Africa Front-end Developer
Larry Wachira, UX/UI designer
- [ ] Remove s from TZ email address

**Comment by DavidLemayian** [comment]
Closed thanks to #78
